services:
  main:
    build: main
    env_file:
      - .env
    ports:
      - ${TOWER_MAIN_LISTEN_PORT}:${TOWER_MAIN_LISTEN_PORT}
    secrets:
      - db-password
      - redis-password
      - auth-jwt-key
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  auth:
    build: auth
    env_file:
      - .env
    ports:
      - "8000:8000"
    secrets:
      - db-password
      - redis-password
      - auth-jwt-key
      - key.pem
      - cert.pem
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    build: db
    env_file:
      - .env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_HOST: ${TOWER_DB_HOST}
      MARIADB_PORT: ${TOWER_DB_PORT}
      MARIADB_USER: ${TOWER_DB_USER}
      MARIADB_PASSWORD_FILE: ${TOWER_DB_PASSWORD_FILE}
      MARIADB_DATABASE: ${TOWER_DB_NAME}
    expose:
      - ${TOWER_DB_PORT}
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    secrets:
      - db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 0s
      interval: 5s
      timeout: 5s 
      retries: 5
  
  redis:
    image: redis:alpine
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis-password
    expose:
      - "6379"
    secrets:
      - redis-password
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    command: sh -c "redis-server --requirepass $(cat $$REDIS_PASSWORD_FILE)"

volumes:
  db-data:

secrets:
  db-password:
    file: secrets/db-password
  redis-password:
    file: secrets/redis-password
  auth-jwt-key:
    file: secrets/auth-jwt-key
  key.pem:
    file: secrets/key.pem
  cert.pem:
    file: secrets/cert.pem